#!/usr/bin/env python3
"""Deterministic fixture-repo generator for the self-serve E2E harness.

Builds a small git repository with synthetic-but-real history: a chain of
feature branches, each merged back to ``main`` with a PR-shaped
``--no-ff`` merge commit (title + body + a ``Fixes #N`` trailer) that
touches both a source file and its test — the exact shape
``codeprobe mine --no-llm`` extracts tasks from (see
``src/codeprobe/mining/extractor.py::_list_merged_prs_git`` and
``tests/test_mine_cli.py::_make_sdlc_repo``, which this generator's merge
shape is modeled on).

Every commit gets a fixed, incrementing ``GIT_AUTHOR_DATE`` /
``GIT_COMMITTER_DATE`` so two runs of ``make_python_fixture_repo`` against
the same parameters produce byte-identical trees (mining task counts and
IDs are stable across CI runs, which the harness's assertions depend on).

Two more variants exist for the harness's negative cases:
``make_ruby_fixture_repo`` (a supported-mining-matrix miss —
``UNSUPPORTED_LANGUAGE``) and the ``dirty=True`` flag on
``make_python_fixture_repo`` (an uncommitted change after generation —
``DIRTY_CHECKOUT``).

Usage (manual inspection):
    python scripts/e2e/make_fixture_repo.py /tmp/fixture --language python
    python scripts/e2e/make_fixture_repo.py /tmp/fixture --language ruby
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

#: _MIN_PAIRED_TASKS in acceptance/../src/codeprobe/analysis/stats.py is 3 —
#: below that, even a real MCP-vs-baseline comparison is REFUSED as
#: incomparable. Default to comfortably more than both that floor and the
#: bead's own ">=2 tasks" floor, so the harness's positive journey exercises
#: a genuinely comparable verdict rather than a REFUSED one.
DEFAULT_FEATURE_COUNT = 5

#: Fixed base timestamp (UTC) for GIT_AUTHOR_DATE/GIT_COMMITTER_DATE.
#: Deliberately not "now" — reproducibility requires a constant, not a
#: moving target every time this script runs. Commit blob/tree hashes never
#: depend on this (git only hashes it into the commit object itself), but a
#: stable date still makes history diffs across CI runs boring to read.
_BASE_TIMESTAMP = datetime(2026, 1, 1, tzinfo=UTC)


def _git_env(commit_index: int) -> dict[str, str]:
    """Fixed author/committer date env vars for the *commit_index*-th commit.

    One synthetic day per commit index, so history reads as an ordinary
    incremental development timeline while staying fully deterministic.
    """
    date = (_BASE_TIMESTAMP + timedelta(days=commit_index)).strftime(
        "%Y-%m-%dT%H:%M:%S %z"
    )
    return {
        "GIT_AUTHOR_NAME": "codeprobe-e2e",
        "GIT_AUTHOR_EMAIL": "e2e@example.invalid",
        "GIT_AUTHOR_DATE": date,
        "GIT_COMMITTER_NAME": "codeprobe-e2e",
        "GIT_COMMITTER_EMAIL": "e2e@example.invalid",
        "GIT_COMMITTER_DATE": date,
    }


def _run_git(repo: Path, *args: str, env: dict[str, str] | None = None) -> None:
    import os

    full_env = {**os.environ, **(env or {})}
    subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
        env=full_env,
    )


def make_python_fixture_repo(
    dest: Path,
    *,
    feature_count: int = DEFAULT_FEATURE_COUNT,
    dirty: bool = False,
) -> Path:
    """Build a Python fixture repo with *feature_count* tested PR-shaped merges.

    Returns the repo path (``dest``, created if absent). Each feature is a
    ``--no-ff`` merge of a branch adding one source module and its pytest
    test — the shape ``codeprobe mine --no-llm`` needs to mine a task from
    (source change + test change in the same merge). A trailing ``chore:``
    commit (README) pads the history toward "a dozen commits" without
    affecting task yield.

    When ``dirty=True``, an untracked file is left in the working tree
    after generation (for the dirty-checkout negative case) — the file is
    a plain source-tree stray, not under any codeprobe-owned path, so
    ``codeprobe run``'s dirty-checkout refusal treats it as offending.
    """
    dest.mkdir(parents=True, exist_ok=True)
    commit_index = 0

    def git(*args: str) -> None:
        nonlocal commit_index
        _run_git(dest, *args, env=_git_env(commit_index))

    _run_git(dest, "init", "-q", "-b", "main")
    _run_git(dest, "config", "user.email", "e2e@example.invalid")
    _run_git(dest, "config", "user.name", "codeprobe-e2e")

    (dest / "README.md").write_text(
        "# E2E fixture repo\n\nGenerated by scripts/e2e/make_fixture_repo.py.\n"
    )
    # Codeprobe's own artifact dirs (.codeprobe/ mining+experiment state,
    # .codeprobe-worktrees*/ trial isolation pool, runs/) are tracked from
    # commit 1 so `git status --porcelain` after mine/run only ever reports
    # genuine customer-visible drift — never codeprobe's own bookkeeping.
    (dest / ".gitignore").write_text(
        ".codeprobe/\n.codeprobe-worktrees*/\nruns/\n"
    )
    git("add", ".")
    commit_index += 1
    git("commit", "-q", "-m", "chore: init fixture repo")

    for i in range(1, feature_count + 1):
        branch = f"feat/feature-{i}"
        git("checkout", "-q", "-b", branch)

        module_path = dest / f"feature_{i}.py"
        module_path.write_text(
            f'"""Feature {i}: adds {i} to its input."""\n\n\n'
            f"def feature_{i}(x: int) -> int:\n"
            f"    return x + {i}\n"
        )
        tests_dir = dest / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / f"test_feature_{i}.py").write_text(
            f"from feature_{i} import feature_{i}\n\n\n"
            f"def test_feature_{i}():\n"
            f"    assert feature_{i}(0) == {i}\n"
            f"    assert feature_{i}(10) == {10 + i}\n"
        )
        git("add", ".")
        commit_index += 1
        git(
            "commit",
            "-q",
            "-m",
            f"feat: add feature {i}\n\nImplements feature_{i}() with unit tests.",
        )

        git("checkout", "-q", "main")
        commit_index += 1
        git(
            "merge",
            "--no-ff",
            "-q",
            "-m",
            f"Merge PR #{i}: add feature {i}\n\n"
            f"Adds feature_{i}() and its test coverage.\n\n"
            f"Fixes #{100 + i}",
            branch,
        )

    if dirty:
        (dest / "untracked_dirty_marker.txt").write_text(
            "left uncommitted on purpose for the dirty-checkout negative case\n"
        )

    return dest


def make_ruby_fixture_repo(dest: Path) -> Path:
    """Build a minimal Ruby-only repo — outside the Py/Go/JS-TS mining matrix.

    A single commit is enough: the language gate (codeprobe-f7rl.20) fires
    before any PR scanning, so this never needs merge history.
    """
    dest.mkdir(parents=True, exist_ok=True)
    _run_git(dest, "init", "-q", "-b", "main")
    _run_git(dest, "config", "user.email", "e2e@example.invalid")
    _run_git(dest, "config", "user.name", "codeprobe-e2e")

    (dest / "lib").mkdir(exist_ok=True)
    (dest / "lib" / "greeter.rb").write_text(
        "class Greeter\n  def hello\n    'hello'\n  end\nend\n"
    )
    (dest / "lib" / "farewell.rb").write_text(
        "class Farewell\n  def bye\n    'bye'\n  end\nend\n"
    )
    _run_git(dest, "add", ".", env=_git_env(0))
    _run_git(dest, "commit", "-q", "-m", "chore: init ruby fixture", env=_git_env(0))
    return dest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("dest", type=Path, help="Destination directory (created).")
    parser.add_argument(
        "--language",
        choices=("python", "ruby"),
        default="python",
        help="Which fixture variant to generate (default: python).",
    )
    parser.add_argument(
        "--feature-count",
        type=int,
        default=DEFAULT_FEATURE_COUNT,
        help=f"Number of tested feature merges (python only, default {DEFAULT_FEATURE_COUNT}).",
    )
    parser.add_argument(
        "--dirty",
        action="store_true",
        help="Leave an untracked file after generation (python only).",
    )
    args = parser.parse_args(argv)

    if args.dest.exists() and any(args.dest.iterdir()):
        print(f"error: {args.dest} already exists and is non-empty", file=sys.stderr)
        return 2

    if args.language == "ruby":
        make_ruby_fixture_repo(args.dest)
    else:
        make_python_fixture_repo(
            args.dest, feature_count=args.feature_count, dirty=args.dirty
        )
    print(f"OK: fixture repo generated at {args.dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
