"""Tests for write_suite_manifest() — auto-emitting suite.toml from mine --goal."""

from __future__ import annotations

import tomllib
from pathlib import Path


def test_write_suite_manifest_creates_file(tmp_path: Path) -> None:
    """suite.toml is written to tasks_dir.parent."""
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    result = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="Codebase navigation",
        task_types=("architecture_comprehension",),
        description="Generated by codeprobe mine --goal navigation",
    )

    assert result == tmp_path / "suite.toml"
    assert result.exists()


def test_write_suite_manifest_toml_parses(tmp_path: Path) -> None:
    """The emitted suite.toml is valid TOML with a [suite] section."""
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    path = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="Code quality comparison",
        task_types=("sdlc_code_change",),
        description="Generated by codeprobe mine --goal quality",
    )

    with path.open("rb") as f:
        data = tomllib.load(f)

    assert "suite" in data
    suite = data["suite"]
    assert suite["name"].startswith("codeprobe-")
    assert suite["eval_goal"] == "Code quality comparison"
    assert suite["task_types"] == ["sdlc_code_change"]
    assert suite["task_dir"] == "tasks"
    assert suite["description"] == "Generated by codeprobe mine --goal quality"


def test_write_suite_manifest_roundtrips_through_loader(tmp_path: Path) -> None:
    """The emitted suite.toml can be loaded by the suite loader."""
    from codeprobe.loaders.suite import load_suite
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    path = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="Codebase navigation",
        task_types=("architecture_comprehension", "micro_probe"),
        description="Generated by codeprobe mine --goal navigation",
    )

    suite = load_suite(path)
    assert suite.name.startswith("codeprobe-")
    assert suite.eval_goal == "Codebase navigation"
    assert suite.task_types == ("architecture_comprehension", "micro_probe")
    assert suite.task_dir == "tasks"


def test_write_suite_manifest_goal_slug_formatting(tmp_path: Path) -> None:
    """Goal name is slugified: lowercased and spaces replaced with hyphens."""
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    path = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="Code quality comparison",
        task_types=("sdlc_code_change",),
        description="test",
    )

    with path.open("rb") as f:
        data = tomllib.load(f)

    name = data["suite"]["name"]
    # Should contain the slugified goal name
    assert "code-quality-comparison" in name
    # Should contain a date-like suffix (YYYY-MM-DD)
    parts = name.split("-")
    # Last 3 parts should be year, month, day
    assert len(parts[-1]) == 2  # day
    assert len(parts[-2]) == 2  # month
    assert len(parts[-3]) == 4  # year


def test_write_suite_manifest_multiple_task_types(tmp_path: Path) -> None:
    """Multiple task_types are serialised as a TOML array."""
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    path = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="General benchmarking",
        task_types=("sdlc_code_change", "micro_probe"),
        description="mixed",
    )

    with path.open("rb") as f:
        data = tomllib.load(f)

    assert data["suite"]["task_types"] == ["sdlc_code_change", "micro_probe"]


def test_write_suite_manifest_empty_task_types(tmp_path: Path) -> None:
    """Empty task_types tuple produces an empty TOML array."""
    from codeprobe.mining.writer import write_suite_manifest

    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()

    path = write_suite_manifest(
        tasks_dir=tasks_dir,
        goal_name="Test",
        task_types=(),
        description="no types",
    )

    with path.open("rb") as f:
        data = tomllib.load(f)

    assert data["suite"]["task_types"] == []
